# Generated by Django 5.0.7 on 2025-06-07 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ratesuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratesuser',
            name='rates',
        ),
        migrations.AddField(
            model_name='ratesuser',
            name='rate',
            field=models.FloatField(default=1, help_text='Valor entre 1 y 5', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
