# Generated by Django 5.0.7 on 2025-06-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_ratesuser_rates_ratesuser_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratesuser',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ratesuser',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
