# Generated by Django 5.0.7 on 2025-05-21 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_imagetypemodel_carouselitemmodel_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la color')),
                ('hex', models.CharField(max_length=255, verbose_name='Hex')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la tamaño')),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='carouselitemmodel',
            options={'ordering': ('order',), 'verbose_name': 'Carousel Item', 'verbose_name_plural': 'Carousel Items'},
        ),
        migrations.CreateModel(
            name='ProductDistributionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colormodel')),
                ('images', models.ManyToManyField(blank=True, related_name='product_distribution', to='main.image')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sizemodel')),
            ],
            options={
                'verbose_name': 'Distribución de Producto',
                'verbose_name_plural': 'Distribuciones de Productos',
                'ordering': ('color', 'size'),
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
