# Generated by Django 5.0.7 on 2025-05-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_colormodel_sizemodel_alter_carouselitemmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetypemodel',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de Imagen', 'verbose_name_plural': 'Tipos de Imagenes'},
        ),
    ]
