# Generated by Django 5.0.7 on 2025-05-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='care',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
