# Generated by Django 5.0.7 on 2025-06-07 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactmodel'),
        ('products', '0003_productmodel_care_productmodel_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasesProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('description', models.TextField(null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('sub_description', models.TextField(null=True)),
                ('priority', models.IntegerField(default=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.image')),
                ('products', models.ManyToManyField(blank=True, related_name='releases', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'Lanzamiento',
                'verbose_name_plural': 'Lanzamientos',
                'ordering': ['priority'],
            },
        ),
    ]
