# Generated by Django 5.0.7 on 2025-06-07 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_releasesproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasesproductmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
