# Generated by Django 5.0.7 on 2025-06-11 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_releasesproductmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
